kind: Issuer
apiVersion: cert-manager.io/v1alpha2

metadata:
  name: letsencrypt
  namespace: {{.Release.Namespace}}

spec:
  acme:
    # The ACME server URL
    # Что бы не попасть в бан, юзать этот server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: service@ruvents.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: acme-account-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            name: ingress
