kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: ingress
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt"
spec:
  tls:
    - secretName: tls-certificate
      hosts:
        - '{{.Values.Application.BaseHost}}'
  rules:
    - host: '{{.Values.Application.BaseHost}}'
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
