include:
  - project: 'infrastructure/templates'
    file:
      - docker.yml

stages:
  - docker
  - deploy

application:
  extends: .common_image
  only:
    - /^devops\//
    - master
  variables:
    DOCKERFILE: |
      FROM golang:1.17-alpine
      
      ADD ./ /app/
      
      RUN cd /app/ \
       && go build -v -o /app/app ./cmd/app
      
      FROM alpine

      COPY --from=0 /app/app /bin/

      CMD app

production:
  stage: deploy
  image: ruvents/helm
  environment:
    name: production
    url: https://telegram.ruvents.dev/
  before_script:
    - chmod 0600 "${KUBECONFIG}"
  script:
    - helm upgrade --install --atomic --cleanup-on-fail --create-namespace --namespace "${CI_PROJECT_PATH_SLUG}" --timeout 1m --values .devops/values.yaml app .devops
      --set Application.Environment="${CI_ENVIRONMENT_NAME}"
      --set Application.RegistryImage="${CI_REGISTRY_IMAGE}"
      --set Application.RegistryImageTag="${CI_COMMIT_TAG:-build-$CI_COMMIT_SHORT_SHA}"
      --set Application.BaseHost="${HOSTNAME}"
      --set Services.SentryDSN="${SENTRY_DSN}"
      --set Secrets.GitLabToken="${GITLAB_TOKEN}"
      --set Secrets.DockerRegistries[0].Username="${DOCKER_REGISTRY_USERNAME}"
      --set Secrets.DockerRegistries[0].Password="${DOCKER_REGISTRY_PASSWORD}"
